# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACToDo-OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RACToDo-OC

  target 'RACToDo-OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry'
pod 'ReactiveCocoa', '2.5'
pod 'FMDB'
end
